spring.application.name=sistema-academico-integrado-api

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_academico_integrado_api
spring.datasource.username=${SEU_USUARIO}
spring.datasource.password=${SUA_SENHA}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration